//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ComentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Int32 PhoneNumber { get; set; }
        public string Comment1 { get; set; }
    }
}
